version: '3.9'

services:
  web:
    image: nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx/www:/var/www/html
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    links:
      - php-fpm
    depends_on:
      - vp
  php-fpm:
    build:
      dockerfile: php-dockerfile
    image: php:8-fpm
    volumes:
      - ../:/var/www/html
  vp:
   image: quay.io/vouch/vouch-proxy
   volumes:
     - ./vouch-proxy/config/:/config/
   ports:
     - 9090:9090
