version: '3.9'

services:
  vp:
    image: quay.io/vouch/vouch-proxy
    volumes: 
      - ./vouch-proxy/config/config.yml:/config/config.yml
    ports:
      - 9090:9090
  nginx:
    image: nginx
    depends_on:
      - vp
    volumes:
      - './nginx-conf/server.conf:/etc/nginx/conf.d/server.conf'
    ports:
      - 8083:80
